language: go

go:
- "1.9"
- "1.10"

cache:
  directories:
  - vendor
  - $GOPATH/pkg/dep

before_install:
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/golang/lint/golint

install:
- dep ensure -v -vendor-only

script:
- golint -set_exit_status $(go list ./...)
- go test -race -coverpkg ./... -coverprofile coverage.txt -covermode atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
